In [1]:
import pandas as pd
import numpy as np

In [26]:
df = pd.read_excel(r"C:\Users\matur\Downloads\Restaurant_Raw_Dataset.xlsx")

In [27]:
df

,Order_ID,Order_Date,Branch_Name,Customer_ID,Customer_Age_Group,Item_Name,Category,Quantity,Unit_Price (₹),Total_Sales (₹),Cost_Price (₹),Payment_Method,Order_Type,Customer_Rating,Customer_Feedback,Employee_Name,Employee_Feedback,Profit (₹),Profit_Margin (%)
0,ORD00001,09-02-2025 01:43:00,Lakeside,CUST225,45–54,Paneer Tikka,Starters,5,159.19,795.95,586.80,Cash,Takeaway,5.0,Quick service,Neha R.,Helpful,209.15,26.28
1,ORD00002,29-04-2025 12:38:00,Uptown,CUST164,45–54,Gulab Jamun,Desserts,3,349.56,1048.68,664.72,Credit Card,Takeaway,5.0,Loved it,Rahul K.,Friendly,383.96,36.61
2,ORD00003,01-02-2025 02:33:00,Lakeside,CUST529,25–34,Mojito,Drinks,2,290.53,581.06,367.88,UPI,Dine-In,1.0,Quick service,Sarah L.,Good behavior,213.18,36.69
3,ORDXYZ,27-03-2025 19:58:00,Lakeside,CUST818,45–54,Chicken Wings,Starters,3,155.03,465.09,321.71,Cash,Takeaway,5.0,Good taste,Priya S.,Quick service,143.38,30.83
4,ORD00005,12-03-2025 01:39:00,Hillview,CUST321,55+,Chocolate,Ice Cream,1,401.65,401.65,229.20,Cash,Dine-In,2.0,Quick service,Meena C.,Professional,172.45,42.94
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,ORD03562,04-04-2025 23:07:00,Hillview,CUST544,18–24,Strawberry,Ice Cream,5,105.1,525.50,337.50,Debit Card,Takeaway,5.0,Very tasty,Sarah L.,Friendly,188.00,35.78
4996,ORD00408,14-02-2025 14:53:00,Hillview,CUST993,35–44,Pasta Alfredo,Main,2,218.5,437.00,357.60,Debit Card,Delivery,4.0,Very tasty,Rahul K.,Polite,79.40,18.17
4997,ORD04998,09-04-2025 12:25:00,Hillview,CUST842,25–34,Ice Cream Sundae,Desserts,1,384.54,384.54,307.46,UPI,Delivery,3.0,Nice food,Neha R.,Professional,77.08,20.04
4998,ORD03245,21-02-2025 17:04:00,Lakeside,CUST260,45–54,Chicken Wings,Starters,4,286.18,1144.72,929.45,UPI,Delivery,2.0,Okay,Rajesh B.,Good behavior,215.27,18.81
4999,ORD01008,18-04-2025 08:13:00,Lakeside,CUST987,35–44,Strawberry,Ice Cream,2,438.02,876.04,516.63,Debit Card,Delivery,2.0,Loved it,Sarah L.,Friendly,359.41,41.03

In [28]:
# Remove duplicates
df = df.drop_duplicates()

In [33]:
df.loc[:, "Order_Date"] = pd.to_datetime(
    df["Order_Date"],
    errors="coerce",
    dayfirst=True
)

In [34]:
df

,Order_ID,Order_Date,Branch_Name,Customer_ID,Customer_Age_Group,Item_Name,Category,Quantity,Unit_Price (₹),Total_Sales (₹),Cost_Price (₹),Payment_Method,Order_Type,Customer_Rating,Customer_Feedback,Employee_Name,Employee_Feedback,Profit (₹),Profit_Margin (%)
0,ORD00001,2025-02-09 01:43:00,Lakeside,CUST225,45–54,Paneer Tikka,Starters,5,159.19,795.95,586.80,Cash,Takeaway,5.0,Quick service,Neha R.,Helpful,209.15,26.28
1,ORD00002,2025-04-29 12:38:00,Uptown,CUST164,45–54,Gulab Jamun,Desserts,3,349.56,1048.68,664.72,Credit Card,Takeaway,5.0,Loved it,Rahul K.,Friendly,383.96,36.61
2,ORD00003,2025-02-01 02:33:00,Lakeside,CUST529,25–34,Mojito,Drinks,2,290.53,581.06,367.88,UPI,Dine-In,1.0,Quick service,Sarah L.,Good behavior,213.18,36.69
3,ORDXYZ,2025-03-27 19:58:00,Lakeside,CUST818,45–54,Chicken Wings,Starters,3,155.03,465.09,321.71,Cash,Takeaway,5.0,Good taste,Priya S.,Quick service,143.38,30.83
4,ORD00005,2025-03-12 01:39:00,Hillview,CUST321,55+,Chocolate,Ice Cream,1,401.65,401.65,229.20,Cash,Dine-In,2.0,Quick service,Meena C.,Professional,172.45,42.94
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4989,ORD04990,2025-06-20 08:00:00,Riverside,CUST846,35–44,Pasta Alfredo,Main,3,265.90,797.70,487.86,UPI,Delivery,2.0,Quick service,Amit P.,Attentive,309.84,38.84
4991,ORD04992,2025-06-12 15:01:00,Lakeside,CUST857,55+,Strawberry,Ice Cream,5,383.11,1915.55,1105.21,Debit Card,Takeaway,4.0,Okay,Priya S.,Professional,810.34,42.30
4992,ORD04993,2025-02-03 13:41:00,Lakeside,CUST851,35–44,Mojito,Drinks,1,260.72,260.72,171.95,UPI,Takeaway,2.0,Loved it,Rajesh B.,Helpful,88.77,34.05
4996,ORD00408,2025-02-14 14:53:00,Hillview,CUST993,35–44,Pasta Alfredo,Main,2,218.50,437.00,357.60,Debit Card,Delivery,4.0,Very tasty,Rahul K.,Polite,79.40,18.17
4997,ORD04998,2025-04-09 12:25:00,Hillview,CUST842,25–34,Ice Cream Sundae,Desserts,1,384.54,384.54,307.46,UPI,Delivery,3.0,Nice food,Neha R.,Professional,77.08,20.04

In [35]:
df = df.dropna(subset=["Order_Date"])

In [47]:
# Convert numeric columns
numeric_cols = [
    "Quantity",
    "Unit_Price (₹)",
    "Total_Sales (₹)",
    "Cost_Price (₹)",
    "Profit (₹)",
    "Profit_Margin (%)",
    "Customer_Rating"
]
# If df is a filtered DataFrame
df = df.copy()
# Convert columns to numeric
for col in numeric_cols:
    df.loc[:, col] = pd.to_numeric(df[col], errors="coerce")

In [36]:
# Remove invalid values
df = df[df["Quantity"] > 0]
df = df[df["Unit_Price (₹)"] > 0]
df = df[df["Total_Sales (₹)"] > 0]
df = df[df["Cost_Price (₹)"] > 0]
df = df[df["Profit (₹)"] >= 0]
df = df[df["Profit_Margin (%)"] <= 100]

In [37]:
# Payment validation
valid_payment = ["Cash","UPI","Credit Card","Debit Card"]
df = df[df["Payment_Method"].isin(valid_payment)]

In [38]:
# Order type validation
valid_order = ["Dine-In","Takeaway","Delivery"]
df = df[df["Order_Type"].isin(valid_order)]

In [39]:
# Age validation
valid_age = ["18–24","25–34","35–44","45–54","55+"]
df = df[df["Customer_Age_Group"].isin(valid_age)]

In [40]:
# Valid Order ID
df = df[df["Order_ID"].str.match(r"^ORD\d+$")]

In [41]:
# Remove outliers
Q1 = df["Total_Sales (₹)"].quantile(0.25)
Q3 = df["Total_Sales (₹)"].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

df = df[
    (df["Total_Sales (₹)"] >= lower) &
    (df["Total_Sales (₹)"] <= upper)
]

In [42]:
df = df.reset_index(drop=True)

In [44]:
df

,Order_ID,Order_Date,Branch_Name,Customer_ID,Customer_Age_Group,Item_Name,Category,Quantity,Unit_Price (₹),Total_Sales (₹),Cost_Price (₹),Payment_Method,Order_Type,Customer_Rating,Customer_Feedback,Employee_Name,Employee_Feedback,Profit (₹),Profit_Margin (%)
0,ORD00001,2025-02-09 01:43:00,Lakeside,CUST225,45–54,Paneer Tikka,Starters,5,159.19,795.95,586.80,Cash,Takeaway,5.0,Quick service,Neha R.,Helpful,209.15,26.28
1,ORD00002,2025-04-29 12:38:00,Uptown,CUST164,45–54,Gulab Jamun,Desserts,3,349.56,1048.68,664.72,Credit Card,Takeaway,5.0,Loved it,Rahul K.,Friendly,383.96,36.61
2,ORD00003,2025-02-01 02:33:00,Lakeside,CUST529,25–34,Mojito,Drinks,2,290.53,581.06,367.88,UPI,Dine-In,1.0,Quick service,Sarah L.,Good behavior,213.18,36.69
3,ORD00005,2025-03-12 01:39:00,Hillview,CUST321,55+,Chocolate,Ice Cream,1,401.65,401.65,229.20,Cash,Dine-In,2.0,Quick service,Meena C.,Professional,172.45,42.94
4,ORD00006,2025-01-18 10:07:00,Uptown,CUST228,35–44,Ice Cream Sundae,Desserts,5,158.18,790.90,624.39,Cash,Takeaway,2.0,Okay,Rahul K.,Professional,166.51,21.05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,ORD01035,2025-02-02 06:59:00,Hillview,CUST665,25–34,Paneer Tikka,Starters,3,282.72,848.16,477.97,Cash,Dine-In,2.0,Nice food,Sarah L.,Attentive,370.19,43.65
996,ORD01036,2025-02-14 21:49:00,Hillview,CUST681,25–34,Veg Biryani,Main,1,424.36,424.36,285.29,Cash,Delivery,3.0,Good taste,Amit P.,Good behavior,139.07,32.77
997,ORD01037,2025-02-17 14:54:00,Uptown,CUST251,18–24,Chocolate,Ice Cream,2,317.92,635.84,369.40,UPI,Delivery,1.0,Loved it,John D.,Polite,266.44,41.90
998,ORD01038,2025-03-07 12:34:00,Riverside,CUST572,25–34,Ice Cream Sundae,Desserts,1,136.88,136.88,83.42,UPI,Takeaway,5.0,Nice food,Meena C.,Quick service,53.46,39.06
999,ORD01039,2025-05-16 05:03:00,Riverside,CUST908,45–54,Pasta Alfredo,Main,2,303.79,607.58,410.69,Cash,Takeaway,5.0,Good taste,Sarah L.,Helpful,196.89,32.41

In [45]:
# Save cleaned dataset
df.to_excel("Restaurant_Clean_Dataset.xlsx", index=False)

In [46]:
print("Dataset cleaned successfully.")
print("Rows:", len(df))

Dataset cleaned successfully.
Rows: 1000